server:
  port: 8183

elastic-query-config:
  text-field: text

elastic-config:
  index-name: contract-index
  connection-url: http://localhost:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000
  is-repository: true
