contract-search-service:
  version: v1

server:
  port: 8183
  servlet:
    context-path: /contract-search-service

elastic-query-config:
  text-field: text

elastic-config:
  index-name: contract-index
  connection-url: http://localhost:9200
  connection-timeout: 5000
  socket-timeout: 30000
  is-repository: true

user-config:
  username: test
  password: '{cipher}e014416a74e43326dd936e2b89a9194ef1ac9ca45fe024440070c7f77824469e'
  roles: USER

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

security:
  paths-to-ignore: /api-docs
