contract-search-service:
  version: v1

server:
  port: 8183
  servlet:
    context-path: /contract-search-service

elastic-query-config:
  text-field: text

elastic-config:
  index-name: contract-index
  connection-url: http://localhost:9200
  connection-timeout: 5000
  socket-timeout: 30000
  is-repository: true
